# Generated by Django 3.1.5 on 2021-01-23 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('name', models.CharField(max_length=100, verbose_name='animal name')),
                ('species', models.CharField(max_length=100, verbose_name='animal species')),
                ('color', models.CharField(max_length=50, verbose_name='animal name')),
                ('sex', models.CharField(max_length=25, verbose_name='animal name')),
                ('weight', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
